/**
 * App texts
 */
this.texts = {
    ru: {
        language: "Русский",
        languageChanged: "Вы изменили язык на русский",

        place: "Место",
        points: "Баллы",
        workoutDay: "Тренировки",
        workoutByBodyType: "Тренировки по типу фигуры",
        nutritionSended: "Рецепт успешно отправлен!",
        exerciseSended: "Упражнения успешно отправлен!",
        selectSocial: "Отправьте в ВК или Телеграм",
        statsTitile: "Статистика активности и баллы",
        instruction: "Инструкция",
        activeThemeDark: "Тёмная тема",
        activeThemeLight: "Светлая тема",
        genderMale: "Мужской",
        genderFemale: "Женский",
        genderMaleChanged: "Вы изменили упражнения и тренировки на мужской",
        genderFemaleChanged: "Вы изменили упражнения и тренировки на женский",
        darkThemeActive: "Тёмная тема активирована",
        lightThemeActive: "Светлая тема активирована",
        nutritionMuscleBuilding: "Наращивание мышц",
        nutritionMuscleBuildingChanged: "Питание изменены на Наращивание мышц",
        nutritionWeightLoss: "Снижение веса",
        nutritionWeightLossChanged: "Питание изменены на Снижение веса",
        day: "День",
        sendToVk: "Отправить в ВК",
        sendToTg: "Отправить в Телеграм",
        reloading: "Проверяем ...",
        cancel: "Отменить",
        vkNotIntegrated: "ВК не интегрирован.",
        tgNotIntegrated: "Телеграм не интегрирован.",
        tgIntegrated: "Телеграм успешно интегрирован!",
        vkIntegrated: "ВК успешно интегрирован!",
        sendToSocial: "Отправить в социальные сети",
        playExerciseClosed: "Вы закрыли упражнения, чтобы начать заново сделайте полный экран",
        finishedExercise: "Вы успешно закончили упражнение",
        relaxCircle: "Отдыхаем между кругами",
        startThirdCircle: "Начали третий круг",
        startSecondCircle: "Начали второй круг",
        startFirstCircle: "Начали первый круг",
        start: "Начать",
        stop: "Остановить",
        repetitionCircle: "Круг (Повторяем 2-3 раза)",
        videoNotAdded: "Вы ещё не добавили Видео в закладки",
        exersicesNotAdded: "Вы ещё не добавили Упражнения в закладки",
        nutritionNotAdded: "Вы ещё не добавили Питание в закладки",
        sended: "Отправлено!",
        checkIntegration: "Проверить интеграцию",
        settingInfo: "Mожно отправлять упражнения, рецепты и много другое.\nБот ВК: https://vk.com/fit_smart_bot.\nБот Телеграм: https://t.me/fit_smart_bot.\nДля подключения нужно отправит ID приложения.",
        appFunctions: [
            "1. Добавить в закладки. Это красная кнопка на пульте.",
            "2. Функция сделать полный экран. Это зеленая кнопка на пульте.",
            "3. Изменить оформление. Это желтая кнопка на пульте.",
            "4. Изменить язык. Это синяя кнопка на пульте."
        ],

        doFullscreen: "-- Сделайте полный экран, чтобы посмотреть полную инструкцию и начать упражнения ---"
    },
    en: {
        language: "English",
        languageChanged: "You changed the language to english",

        place: "Place",
        points: "Points",
        workoutDay: "Workouts",
        workoutByBodyType: "Body Type Workouts",
        nutritionSended: "Recipe sent successfully!",
        exerciseSended: "Exercise sent successfully!",
        selectSocial: "Send to VK or Telegram",
        statsTitile: "Activity Statistics and points",
        instruction: "Instructions",
        activeThemeDark: "Dark theme",
        activeThemeLight: "Light theme",
        genderMale: "Male",
        genderFemale: "Female",
        genderMaleChanged: "You changed the exercises and workouts to male",
        genderFemaleChanged: "You changed the exercises and workouts to female",
        darkThemeActive: "Dark theme activated",
        lightThemeActive: "Light theme activated",
        nutritionMuscleBuilding: "Muscle building",
        nutritionMuscleBuildingChanged: "Nutrition changed to build muscle",
        nutritionWeightLoss: "Weight loss",
        nutritionWeightLossChanged: "Nutrition changed for weight Loss",
        day: "Day",
        sendToVk: "Send to VK",
        sendToTg: "Send to Telegram",
        reloading: "Checking ...",
        cancel: "Cancel",
        vkNotIntegrated: "VK is not integrated.",
        tgNotIntegrated: "Telegram is not integrated.",
        tgIntegrated: "Telegram successfully integrated!",
        vkIntegrated: "VK has been successfully integrated!",
        sendToSocial: "Send to social networks",
        playExerciseClosed: "You closed the exercise to start again make a full screen",
        finishedExercise: "You completed the exercise successfully",
        relaxCircle: "Resting between roundes",
        startThirdCircle: "Started the third round",
        startSecondCircle: "Started the second round",
        startFirstCircle: "Started the first round",
        start: "Start",
        stop: "Stop",
        repetitionCircle: "Round (Repeat 2-3 times)",
        videoNotAdded: "You haven't added the Video to your bookmarks yet",
        exersicesNotAdded: "You haven't added the Exercises to your bookmarks yet",
        nutritionNotAdded: "You haven't added Food to your bookmarks yet",
        sended: "Sent!",
        checkIntegration: "Check integration",
        settingInfo: "You can send exercises, recipes, and much more.\nBot VK: https://vk.com/fit_smart_bot.\nBot Telegram: https://t.me/fit_smart_bot.\nTo connect, you will need to send the appMain ID.",
        appFunctions: [
            "1. Add to bookmarks. This is the red button on the remote.",
            "2. A function to make it full screen. This is the green button on the remote.",
            "3. Change the design. This is the yellow button on the remote.",
            "4. Change the language. This is the blue button on the remote."
        ],

        doFullscreen: "--- Make a full screen to view the full instructions and start the exercise ---"
    }
};